import Head from 'next/head';
import Image from 'next/image';
import Footer from '../components/home/Footer';
import Header from '../components/home/Header';
import { FaDiscord } from 'react-icons/fa';
import { useState } from 'react';

export default function Home() {
  const [cheats, enableCheats] = useState(false);
  let cheatText = cheats ? 'Show Cheats: Enabled' : 'Show Cheats: Disabled';
  let cheatColor = cheats ? 'border-green-600' : 'border-red-500';

  return (
    <div className=''>
      <Head>
        <title>QOL Hub</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <main className='my-10 mx-5 h-screen'>
        <div className='text-3xl text-center'>
          A Safe Place To Find Unratted & Useful Hypixel Mods
        </div>
        <div className='justify-center md:flex text-xs sm:text-lg'>
          <div className='text-center mt-4 grid grid-cols-2 gap-4'>
            <a href='https://discord.gg/qolhub'>
              <button className='bg-blue-700 py-3 px-6 rounded-lg h-full my-auto opacity-80 hover:opacity-100 shadow-lg'>
                <FaDiscord className='inline-block mr-3 w-6 translate-y-[-3px]' />
                Join our Discord
              </button>
            </a>
            <button
              className={`py-3 px-6 border ${cheatColor} rounded-lg shadow-lg`}
              onClick={(e) => {
                enableCheats(!cheats);
              }}
            >
              {cheatText}
            </button>
          </div>
        </div>
        <div className='relative mx-auto my-10 w-11/12 lg:w-1/2 '>
          <div className='flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none'>
            <svg
              aria-hidden='true'
              className='w-5 h-5 text-gray-400'
              fill='none'
              stroke='currentColor'
              viewBox='0 0 24 24'
              xmlns='http://www.w3.org/2000/svg'
            >
              <path
                stroke-linecap='round'
                stroke-linejoin='round'
                stroke-width='2'
                d='M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z'
              ></path>
            </svg>
          </div>
          <input
            type='search'
            id='default-search'
            className='block p-4 pl-10 w-full text-sm rounded-lg border border-gray-400 placeholder-gray-400 focus:ring-blue-500 focus:border-blue-500'
            placeholder='Search for Mods'
            required
          />
        </div>
      </main>
      <Footer />
    </div>
  );
}
